org: discoverooapi
service: api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  app:
    handler: app.handler
    events:
      - http: 
          path: ANY /
          method: get 
          cors: true 
          integration: LAMBDA
      - http:
          path: ANY {proxy}
          method: get 
          cors: true 
          integration: LAMBDA